#listen port
listen:
  port: "8888"
  
#log level
log:
  level: "debug"

#db mysql
db:
  name: "l0_db"
  user: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3306

msgnet:
  addresses: ["127.0.0.1:10001"]