net:
  maxPeers: MAX_PEERS
  bootstrapNodes: []
  listenAddr: "LISTEN_ADDR"
  privatekey: "PRIVATE_KEY"
  
  msgnet:
    routeAddress: ["ROUTE_ADDR"]

log:
  level: "LOG_LEVEL"

jrpc:
  enabled: ENABLE_JSONRPC
  port: "RPC_PORT"

blockchain:
  id: "CHAIN_ID"
  datadir: "DATA_DIR"

issueaddr:
  addr: ["ISSUE_ADDR"]

#consensus
consensus:
  plugin: "CONSENSUS"

  noops:
    blockSize: BLOCK_SIZE
    blockInterval: 10s

  lbft:
    id: "LBFT_ID"
    "N": N_VALUE
    Q: Q_VALUE
    K: K_VALUE
    blockSize: 2000 
    blockTimeout: 8s
    blockInterval: 10s
    blockDelay: 10s
    viewChange: 5s
    resendViewChange: 5s
    viewChangePeriod: 0s
    nullRequest: 5s    
    bufferSize: 100    
    maxConcurrentNumFrom: 10
    maxConcurrentNumTo: 10

