deploy_server: "http://127.0.0.1:8888"

base_dir: "data/ca_server/"

root_key: "data/ca_server/ca_cert/ca.key"

root_crt: "data/ca_server/ca_cert/ca.crt"

ca_cert_dir: "data/ca_server/ca_cert"

agent_cert_dir: "data/agent/agent_cert/"
